services:
  policy-service:
    build:
      context: ./apps/policy-engine
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    command: node dist/src/main.js
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - PORT=${PORT}
    ports:
      - '3002:3000'
    depends_on:
      policy_engine-db: { condition: service_healthy }
      redis: { condition: service_healthy }
    restart: unless-stopped

  # ----- Redis RabbitMQ ----
  policy_engine-db:
    image: postgres:15
    environment:
      POSTGRES_DB: policy-engine_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - '5435:5432'
    volumes:
      - policy_engine-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # RabbitMQ(arm64 compatible)
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    ports:
      - '5673:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: unless-stopped

  #Redis
  redis:
    image: redis:7-alpine
    container_name: redis
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  policy_engine-db-data:
  redis_data: